apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opspilot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opspilot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opspilot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opspilot.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "opspilot.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: opspilot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
            - name: GEMINI_MODEL
              value: {{ .Values.env.GEMINI_MODEL | quote }}
            - name: AUDIT_BACKEND
              value: {{ .Values.env.AUDIT_BACKEND | quote }}
            - name: AUDIT_TABLE
              value: {{ .Values.env.AUDIT_TABLE | quote }}
            - name: AUDIT_S3_BUCKET
              value: {{ .Values.env.AUDIT_S3_BUCKET | quote }}
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: GOOGLE_API_KEY
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: GITHUB_TOKEN
                  optional: true
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: GITHUB_WEBHOOK_SECRET
                  optional: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
